# @package _global_
model:
  nuisance_count_bins: 20
  noise_std_X: 0.01
  noise_std_Y: 0.05
  nuisance_lr: 0.001
  batch_size: 64

  target_count_bins: 5
  target_nce_bins: 70
  num_epochs: 10000
  target_num_epochs: 5000