# @package _global_
model:
  _target_: src.models.infs.PluginINFs
  name: infs_plugin

  # nuisance hparams
  nuisance_count_bins: ???           # number of knots for nuisance, n_{\text{knots,N}}
  nuisance_hid_dim_multiplier: 10    # ratio between the dimentionalities of the representation and the outcome
  noise_std_X: ???                   # noise regularization for covariates, \sigma^2_x
  noise_std_Y: ???                   # noise regularization for outcomes, \sigma^2_y
  nuisance_lr: ???                   # learning rate for the nuisance flow (CNF), \eta_\text{N}
  batch_size: ???                    # batch size for the nuisance network, b_N
  num_epochs: 5000                   # n_{\text{iter,N}}

  # General hparams
  n_mc: 10000                        # number of samples for ATE estimation

  # Tuning
  tune_hparams: True
  tune_range: 50                     # number of trials for random search
  tune_type: choice
  hparams_grid:
    nuisance_count_bins:
      - 5
      - 10
      - 20
    noise_std_X:
      - 0.0
      - 0.01
      - 0.05
      - 0.1
    noise_std_Y:
      - 0.0
      - 0.01
      - 0.05
      - 0.1
    nuisance_lr:
      - 1e-3
      - 5e-3
    batch_size:
      - 32
      - 64