# @package _global_
model:
  _target_: src.models.plugins.PluginMDN
  name: mdn_plugin

  # MDN hparams
  nuisance_num_comp: 5               # number of mixture components, n_C
  nuisance_hid_dim_multiplier: 10    # ratio between the dimentionalities of the representation and the outcome
  noise_std_X: 0.01                  # noise regularization for covariates, \sigma^2_x
  noise_std_Y: 0.01                  # noise regularization for outcomes, \sigma^2_y
  nuisance_lr: 0.005                 # learning rate for the MDN, \eta
  batch_size: 64                     # batch size for the nuisance network, b
  num_epochs: 5000                   # n_{\text{iter}}

  # General hparams
  n_mc: 10000                        # number of samples for ATE estimation

  # Tuning
  tune_hparams: True
  tune_range: 50                     # number of trials for random search
  tune_type: choice
  hparams_grid:
    nuisance_num_comp:
      - 5
      - 10
      - 20
    noise_std_X:
      - 0.0
      - 0.01
      - 0.05
      - 0.1
    noise_std_Y:
      - 0.0
      - 0.01
      - 0.05
      - 0.1
    nuisance_lr:
      - 1e-3
      - 5e-3
    batch_size:
      - 32
      - 64