# @package _global_
model:
  nuisance_count_bins: 5
  noise_std_X: 0.1
  noise_std_Y: 0.01
  nuisance_lr: 0.005
  batch_size: 32

  nuisance_hid_dim_multiplier: 30
  num_epochs: 15000
  target_num_epochs: 5000
  target_count_bins: 10