# @package _global_
dataset:
  _target_: src.data.HCMNIST    # Will be dynamically instantiated
  name: hcmnist
  normalize_out: True           # Normalize outcome
  seed: 10

model:
  dim_treat: 1
  dim_cov: 785
  dim_out: 1