# @package _global_
dataset:
  _target_: src.data.IHDP     # Will be dynamically instantiated
  name: ihdp
  normalize_out: True         # Normalize outcome
  k_fold: 10

model:
  dim_treat: 1
  dim_cov: 25
  dim_out: 1