# @package _global_
dataset:
  _target_: src.data.NoisyMoons     # Will be dynamically instantiated
  name: noisy_moons
  seed: 42
  n_samples: 1000
  k_fold: 10
  normalize_out: True               # Normalize outcome

  noise: 0.75                       # Sigma

model:
  dim_treat: 1
  dim_cov: 2
  dim_out: 2