# @package _global_
dataset:
  _target_: src.data.TobaccoControlProgram  # Will be dynamically instantiated
  name: tobacco
  normalize_out: True                       # Normalize outcome
  test_size: 0.0001

model:
  dim_treat: 1
  dim_cov: 5
  dim_out: 1